{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Codegen.Proto exposing
    ( CSMainType(..), SCMainType(..), CSMain, SCMain
    , cSMainDecoder, sCMainDecoder
    , toCSMainEncoder, toSCMainEncoder
    )

{-| ProtoBuf module: `Codegen.Proto`

This module was generated automatically using

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 1.0.0-beta-1
  - [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.0.0) 1.0.0
  - `protoc` 3.14.0
  - the following specification file:
      - `root.proto`


# Model

@docs CSMainType, SCMainType, CSMain, SCMain


# Decoder

@docs cSMainDecoder, sCMainDecoder


# Encoder

@docs toCSMainEncoder, toSCMainEncoder

-}

import Protobuf.Decode as Decode
import Protobuf.Encode as Encode



-- MODEL


{-| CSMainType
-}
type CSMainType
    = CsTest
    | CsTest2
    | UnrecognizedCSMainType_ Int


{-| SCMainType
-}
type SCMainType
    = ScTest2
    | UnrecognizedSCMainType_ Int


{-| CSMain
-}
type alias CSMain =
    { type_ : CSMainType
    }


{-| SCMain
-}
type alias SCMain =
    { type_ : SCMainType
    , test : String
    }



-- DECODER


cSMainTypeDecoder : Decode.Decoder CSMainType
cSMainTypeDecoder =
    Decode.int32
        |> Decode.map
            (\value ->
                case value of
                    0 ->
                        CsTest

                    1 ->
                        CsTest2

                    v ->
                        UnrecognizedCSMainType_ v
            )


sCMainTypeDecoder : Decode.Decoder SCMainType
sCMainTypeDecoder =
    Decode.int32
        |> Decode.map
            (\value ->
                case value of
                    0 ->
                        ScTest2

                    v ->
                        UnrecognizedSCMainType_ v
            )


cSMainDecoder : Decode.Decoder CSMain
cSMainDecoder =
    Decode.message (CSMain CsTest)
        [ Decode.optional 1 cSMainTypeDecoder setType_
        ]


sCMainDecoder : Decode.Decoder SCMain
sCMainDecoder =
    Decode.message (SCMain ScTest2 "")
        [ Decode.optional 1 sCMainTypeDecoder setType_
        , Decode.optional 2 Decode.string setTest
        ]



-- ENCODER


toCSMainTypeEncoder : CSMainType -> Encode.Encoder
toCSMainTypeEncoder value =
    Encode.int32 <|
        case value of
            CsTest ->
                0

            CsTest2 ->
                1

            UnrecognizedCSMainType_ v ->
                v


toSCMainTypeEncoder : SCMainType -> Encode.Encoder
toSCMainTypeEncoder value =
    Encode.int32 <|
        case value of
            ScTest2 ->
                0

            UnrecognizedSCMainType_ v ->
                v


toCSMainEncoder : CSMain -> Encode.Encoder
toCSMainEncoder model =
    Encode.message
        [ ( 1, toCSMainTypeEncoder model.type_ )
        ]


toSCMainEncoder : SCMain -> Encode.Encoder
toSCMainEncoder model =
    Encode.message
        [ ( 1, toSCMainTypeEncoder model.type_ )
        , ( 2, Encode.string model.test )
        ]



-- SETTERS


setType_ : a -> { b | type_ : a } -> { b | type_ : a }
setType_ value model =
    { model | type_ = value }


setTest : a -> { b | test : a } -> { b | test : a }
setTest value model =
    { model | test = value }
